# Generated by Django 5.2.3 on 2025-06-17 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Customer_id',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Customername',
            new_name='username',
        ),
        migrations.AddField(
            model_name='customer',
            name='auth_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 17, 8, 11, 0, 339864, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
